In [2]:
import pandas as pd
import ast

#Leer la base de datos
file_path = "DBrecipes1.csv"
recipe_df = pd.read_csv(file_path, encoding='latin-1')

recipe_df.head()

,Unnamed: 0,recipe_id,recipe_name,aver_rate,image_url,calories,servings,prep_time_hour,prep_time_min,ingredients_quantities,ingredients_list
0,0,0,Arroz aguado,5.00,https://cdn0.recetasgratis.net/es/posts/6/9/6/...,330,3,0,40,"['1 kg', '1 taza', '4', '1 ramo', '1 cucharada...","['pollo', 'arroz', 'tomate', 'hierbabuena', 'a..."
1,1,1,Repochetas,4.76,https://www.lacalzadarivas.com/wp-content/uplo...,196,10,0,30,"['10', '300 gramos', '1 libra', '1', '500 ml',...","['tortillas de maiz', 'queso', 'frijoles', 're..."
2,2,2,Tibio de pinol,4.57,https://somossasa.com/wp-content/uploads/2020/...,120,1,0,10,"['1/2 litro', '1/2 taza', '3 rajitas', 'al gus...","['leche', 'pinol', 'canela', 'azucar']"
3,3,3,Gallopinto,4.62,https://www.recetas-nicaragua.com/base/stock/R...,379,8,0,40,"['1 libra', '1 libra', '5 cucharadas', '1', '1']","['arroz', 'frijoles', 'aceite', 'chiltoma', 'c..."
4,4,4,Sopa de albondiga,4.50,https://www.tresjotas.com/wp-content/uploads/2...,283,4,1,20,"['1/2 kg', '1/2 cucharada', 'al gusto', '2', '...","['carne molida', 'maseca', 'ajo molido', 'papa..."

In [3]:
recipe_df["ingredients_quantities"] = recipe_df["ingredients_quantities"].apply(ast.literal_eval)
recipe_df["ingredients_list"] = recipe_df["ingredients_list"].apply(ast.literal_eval)

def combine_ingredients(row):
    quantities = row["ingredients_quantities"]
    ingredients = row["ingredients_list"]
    combined = []

    # Une cantidad con ingrediente (maneja si tienen longitudes diferentes)
    for i in range(min(len(quantities), len(ingredients))):
        combined.append(f"{quantities[i]} de {ingredients[i]}")

    return combined

recipe_df["ingredients_combined"] = recipe_df.apply(combine_ingredients, axis=1)
recipe_df["ingredients_text_combined"] = recipe_df["ingredients_combined"].apply(lambda x: ", ".join(x))

recipe_df["ingredients_text_combined"]

0     1 kg de pollo, 1 taza de arroz, 4 de tomate, 1...
1     10 de tortillas de maiz, 300 gramos de queso, ...
2     1/2 litro de leche, 1/2 taza de pinol, 3 rajit...
3     1 libra de arroz, 1 libra de frijoles, 5 cucha...
4     1/2 kg de carne molida, 1/2 cucharada de masec...
5     2 tazas de harina, 1 1/2 tazas de leche, 3 de ...
6     3 libras de mondongo, 2 cabezas de ajo, 1 de c...
7     2 libras de yuca, 1/2 de repollo, 1/2 de vinag...
8     2 cucharadas de aceite, 1 de cebolla, 2 de chi...
9     1 kg de masa de maiz, 1 kg de queso, 1  1/2 de...
10    2 de platano verde, al gusto de pollo, al gust...
11        2 de huevo, 100 ml de aceite, al gusto de sal
12    3 de platano, 2 cucharadas de mantequilla, 1 1...
13                       2 de tortilla, al gusto de sal
14    1 bote de tomate, 1 cucharada de azucar, 1 die...
15    1 de pollo, 2 tazas de harina, 1 taza de pan r...
16                                       1 vaso de agua
17    3 libras de carne de lomo, 3 de naranja agria,...
18    8 rebanadas de pan de molde, 4 de huevo, 4 lon...
19    1 de huevo, 250 ml de leche, 40 gramos de mant...
20    500 gramos de papa, 2 de zanahoria, 2 de pimie...
21    4 de gelatina, 1 lata de leche evaporada, 1 la...
22    1 cucharada de canela, 3 de clavo de olor, 2 1...
23    1 kg de carne de res, 1 kg de hueso de carde d...
24    500 g de pescado blanco, 1 taza de jugo de lim...
25    10 de tortillas de maiz, 1 taza de salsa verde...
26    500 g de pechuga de pollo, 1 de cebolla, 1 taz...
27    2 tazas de frijoles cocidos, 1 de cebolla, 1 d...
28    2 libras de yuca, 1/2 libra de azucar, 1 libra...
29    250 gramos de cacao, 10 de clavo de olor, 2 li...
30    2 libras de yuca, al gusto de sal, 1/2 de repo...
31    1 de banano, 1 de huevo, 100 ml de leche, 1 cu...
32    200 g de chocolate negro, 150 g de mantequilla...
33    250 g de queso mascarpone, 3 de huevos, 3 cuch...
34    300 g de queso crema, 100 g de galletas tritur...
35    500 ml de nata para montar, 200 ml de leche, 1...
36    2 de mangos maduros, 200 ml de nata liquida, 5...
37    12 de tortillas de maiz, 300 g de salsa verde,...
38    500 g de carne molida, 9 de laminas de lasagna...
39    300 g de arroz bomba, 200 g de mariscos surtid...
40    500 g de pechuga de pollo, 4 cucharadas de sal...
41    400 g de garbanzos cocidos, 1 de cebolla, 200 ...
42    200 g de tamarindo, 1 de azucar, 1 litro de ag...
43    1 de banana, 1 de fresas, 200 ml de leche, 1 c...
44    4 de limones, 1/2 taza de azucar, al gusto de ...
45    500 ml de leche, 50 g de chocolate negro, 1 cd...
46    1 litro de zumo de naranja, 2 de manzana picad...
47    400 g de pasta, 50 g de queso parmesano, 30 ml...
48    2 de filetes de res, 2 dientes de ajo, 1 cdita...
49    1 taza de quinoa cocida, 1/2 taza de tomate ch...
50    6 de rebanadas de pan, 3 de huevos, 1/2 taza d...
51    4 de tazas de agua, 1 de bolas de te negro, 2 ...
Name: ingredients_text_combined, dtype: object

In [4]:
recipe_df.isnull().sum()

Unnamed: 0                   0
recipe_id                    0
recipe_name                  0
aver_rate                    0
image_url                    0
calories                     0
servings                     0
prep_time_hour               0
prep_time_min                0
ingredients_quantities       0
ingredients_list             0
ingredients_combined         0
ingredients_text_combined    0
dtype: int64

In [5]:
recipe_df.head()

,Unnamed: 0,recipe_id,recipe_name,aver_rate,image_url,calories,servings,prep_time_hour,prep_time_min,ingredients_quantities,ingredients_list,ingredients_combined,ingredients_text_combined
0,0,0,Arroz aguado,5.00,https://cdn0.recetasgratis.net/es/posts/6/9/6/...,330,3,0,40,"[1 kg, 1 taza, 4, 1 ramo, 1 cucharada, 1, 1, 2...","[pollo, arroz, tomate, hierbabuena, achiote, c...","[1 kg de pollo, 1 taza de arroz, 4 de tomate, ...","1 kg de pollo, 1 taza de arroz, 4 de tomate, 1..."
1,1,1,Repochetas,4.76,https://www.lacalzadarivas.com/wp-content/uplo...,196,10,0,30,"[10, 300 gramos, 1 libra, 1, 500 ml, al gusto,...","[tortillas de maiz, queso, frijoles, repollo, ...","[10 de tortillas de maiz, 300 gramos de queso,...","10 de tortillas de maiz, 300 gramos de queso, ..."
2,2,2,Tibio de pinol,4.57,https://somossasa.com/wp-content/uploads/2020/...,120,1,0,10,"[1/2 litro, 1/2 taza, 3 rajitas, al gusto]","[leche, pinol, canela, azucar]","[1/2 litro de leche, 1/2 taza de pinol, 3 raji...","1/2 litro de leche, 1/2 taza de pinol, 3 rajit..."
3,3,3,Gallopinto,4.62,https://www.recetas-nicaragua.com/base/stock/R...,379,8,0,40,"[1 libra, 1 libra, 5 cucharadas, 1, 1]","[arroz, frijoles, aceite, chiltoma, cebolla]","[1 libra de arroz, 1 libra de frijoles, 5 cuch...","1 libra de arroz, 1 libra de frijoles, 5 cucha..."
4,4,4,Sopa de albondiga,4.50,https://www.tresjotas.com/wp-content/uploads/2...,283,4,1,20,"[1/2 kg, 1/2 cucharada, al gusto, 2, 2, 1, 6, ...","[carne molida, maseca, ajo molido, papa, zanah...","[1/2 kg de carne molida, 1/2 cucharada de mase...","1/2 kg de carne molida, 1/2 cucharada de masec..."

In [6]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
recipe_df.dtypes

Unnamed: 0                     int64
recipe_id                      int64
recipe_name                   object
aver_rate                    float64
image_url                     object
calories                       int64
servings                       int64
prep_time_hour                 int64
prep_time_min                  int64
ingredients_quantities        object
ingredients_list              object
ingredients_combined          object
ingredients_text_combined     object
dtype: object

In [8]:
 
print(str)
#Preprocess ingredents
recipe_df["ingredients_list"] = recipe_df["ingredients_list"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

# Asegurar que no haya NaN ni floats
recipe_df["ingredients_list"] = recipe_df["ingredients_list"].apply(
    lambda x: x if isinstance(x, list) else []
)
recipe_df["text_only"] = recipe_df["ingredients_list"].apply(
    lambda lst: " ".join(lst).lower()
)

# Vectorizar
vectorizer = TfidfVectorizer()
x_ingredients = vectorizer.fit_transform(recipe_df["text_only"])

x_ingredients.shape

<class 'str'>

(52, 175)

In [9]:
scaler = StandardScaler()
x_numerical = scaler.fit_transform(recipe_df[["calories", "servings", "prep_time_hour", "prep_time_min"]])

In [10]:
x_numerical

array([[ 0.24613764, -0.71864839, -0.36539703,  0.75348681],
       [-0.73111994,  2.43301442, -0.36539703,  0.13742841],
       [-1.28538544, -1.61912348, -0.36539703, -1.09468838],
       [ 0.60349302,  1.53253933, -0.36539703,  0.75348681],
       [-0.09663181, -0.26841084,  0.99179193, -0.47862999],
       [-0.55608874,  2.43301442, -0.36539703,  0.44545761],
       [ 0.75664533,  1.53253933, -0.36539703,  1.06151601],
       [ 1.04107104, -0.26841084, -0.36539703,  1.06151601],
       [ 0.58890709,  0.63206425, -0.36539703,  0.44545761],
       [ 1.85059038,  0.63206425, -0.36539703,  1.06151601],
       [ 0.17320797, -1.16888593, -0.36539703,  0.75348681],
       [-1.57710412, -1.16888593, -0.36539703, -1.09468838],
       [-1.06659643, -0.71864839, -0.36539703,  0.93830433],
       [-1.72296346, -1.16888593, -0.36539703, -1.40271758],
       [ 0.96814137, -0.26841084, -0.36539703,  0.13742841],
       [-0.36647159, -0.26841084,  2.34898088,  0.13742841],
       [-2.16054148, -1.61912348, -0.36539703, -1.64914094],
       [ 0.72747346, -1.16888593, -0.36539703,  1.3695452 ],
       [-0.29354192, -0.26841084, -0.36539703, -0.78665918],
       [-0.50503797, -0.26841084,  0.99179193, -1.71074678],
       [-0.37376456,  0.1818267 , -0.36539703,  0.75348681],
       [-1.66461972,  0.1818267 ,  5.06335878, -1.71074678],
       [-0.92073709, -0.26841084, -0.36539703,  0.13742841],
       [ 1.18693038,  0.63206425,  2.34898088, -1.71074678],
       [-0.33729973, -0.26841084, -0.36539703,  0.44545761],
       [ 0.90250467, -0.71864839, -0.36539703,  0.13742841],
       [ 1.34008269, -0.26841084, -0.36539703,  1.06151601],
       [ 0.17320797,  0.1818267 , -0.36539703,  0.75348681],
       [-1.29997137,  2.43301442,  2.34898088, -0.47862999],
       [-0.30083489,  0.63206425,  0.99179193, -1.71074678],
       [ 1.02648511, -0.26841084, -0.36539703,  1.06151601],
       [ 0.2096728 , -0.71864839,  0.99179193, -1.71074678],
       [ 0.46492665,  1.53253933, -0.36539703,  1.06151601],
       [ 0.97543434,  0.63206425, -0.36539703,  0.13742841],
       [ 0.90250467,  2.43301442, -0.36539703,  1.3695452 ],
       [-0.33729973, -0.26841084, -0.36539703,  0.75348681],
       [ 0.02734863,  0.63206425, -0.36539703,  0.44545761],
       [ 0.61078599, -0.26841084, -0.36539703,  0.13742841],
       [ 1.85059038,  0.63206425, -0.36539703,  1.9856036 ],
       [ 1.12129368, -0.26841084, -0.36539703,  1.3695452 ],
       [ 0.75664533, -0.26841084, -0.36539703,  0.44545761],
       [ 0.90250467, -0.26841084, -0.36539703,  0.75348681],
       [-1.28538544, -0.26841084, -0.36539703, -1.09468838],
       [-0.84780742, -1.16888593, -0.36539703, -1.40271758],
       [-1.50417445, -0.26841084, -0.36539703, -0.78665918],
       [-0.48315907, -0.71864839, -0.36539703, -1.09468838],
       [-1.06659643,  0.63206425, -0.36539703, -0.47862999],
       [ 0.68371566, -0.26841084, -0.36539703, -0.17060079],
       [ 1.63180137, -1.16888593, -0.36539703,  0.44545761],
       [ 0.17320797, -0.26841084, -0.36539703, -0.47862999],
       [ 0.24613764, -0.71864839, -0.36539703, -0.17060079],
       [-1.35831511, -0.26841084, -0.36539703, -1.09468838]])

In [11]:
x_combined = np.hstack([x_numerical, x_ingredients.toarray()])
x_combined

array([[ 0.24613764, -0.71864839, -0.36539703, ...,  0.        ,
         0.        ,  0.        ],
       [-0.73111994,  2.43301442, -0.36539703, ...,  0.        ,
         0.        ,  0.        ],
       [-1.28538544, -1.61912348, -0.36539703, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.17320797, -0.26841084, -0.36539703, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.24613764, -0.71864839, -0.36539703, ...,  0.        ,
         0.        ,  0.        ],
       [-1.35831511, -0.26841084, -0.36539703, ...,  0.        ,
         0.        ,  0.        ]], shape=(52, 179))

In [12]:
#Train KNN model
knn = NearestNeighbors(n_neighbors=3, metric="euclidean")
knn.fit(x_combined)

NearestNeighbors(metric='euclidean', n_neighbors=3)

In [13]:
def recommend_recipes(input_features):
    input_features_scaled =scaler.transform([input_features[:4]])
    input_ingredients_transformed = vectorizer.transform([input_features[4]])

    input_combined = np.hstack([input_features_scaled, input_ingredients_transformed.toarray()])
    distances, indeces = knn.kneighbors(input_combined)

    recommendations =recipe_df.iloc[indeces[0]]

    return recommendations[["recipe_name", "calories", "servings", "prep_time_hour", "prep_time_min", "ingredients_text_combined", "image_url"]]

#Example Input
input_features = [350,6,0,50, 'leche, huevo, canela, azucar']
recommendations = recommend_recipes(input_features)
recommendations

c:\Users\Dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

,recipe_name,calories,servings,prep_time_hour,prep_time_min,ingredients_text_combined,image_url
27,Sopa de frijol,320,5,0,40,"2 tazas de frijoles cocidos, 1 de cebolla, 1 d...",https://assets.epicurious.com/photos/63ceae6a4...
8,Enchiladas,377,6,0,35,"2 cucharadas de aceite, 1 de cebolla, 2 de chi...",https://recetasdenicaragua.com/wp-content/uplo...
32,Brownies de chocolate,360,8,0,45,"200 g de chocolate negro, 150 g de mantequilla...",https://i.blogs.es/22b5c5/brownie/1200_900.jpg